language: node_js
node_js:
  - "0.10"
  - "0.12"

# use docker for travis
sudo: false

# set these variables from the query. travis seems to not like forking openssl
before_script:
- export FINGERPRINT_DEFAULT=`openssl x509  -noout -fingerprint -sha1 -in <(openssl x509 -in <(openssl s_client -connect api.cloud.appcelerator.com:443 -prexit 2>/dev/null))`
- export FINGERPRINT_TEST=`openssl x509  -noout -fingerprint -sha1 -in <(openssl x509 -in <(openssl s_client -connect preprod-api.cloud.appctest.com:443 -prexit 2>/dev/null))`

notifications:
  flowdock: 
    secure: WsRft17mb7sF8N+9ZES51uArIi2DXDD5boQi7H3B+F415MmiMc2RdSHsheoAKzee22morisDaeYhR2ogB06jqygCtcMftjUaz9K/7dG6xaAuxX/usV20unHI1wyuGsx9tKQt84ZQJMjy8GtMfyNbhI/TF703ui4dSHhMjVHyqtg=
